// examples/svelte-app/src/App.svelte
<script lang="ts">
  import { button } from './styles';

  let ghost = $state(false);
</script>

<main class="page">
  <h1>typestyles + Svelte</h1>
  <p>Typed component styles with ordinary <code>class</code> bindings.</p>
  <button type="button" class={button({ ghost })} onclick={() => (ghost = !ghost)}>
    {ghost ? 'Ghost' : 'Primary'}
  </button>
</main>

<style>
  .page {
    max-width: 40rem;
    margin: 2rem auto;
    padding: 0 1rem;
    font-family:
      system-ui,
      -apple-system,
      sans-serif;
  }
</style>

// examples/vue-app/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { button } from './styles';

const ghost = ref(false);
</script>

<template>
  <main class="page">
    <h1>typestyles + Vue</h1>
    <p>Typed component styles with ordinary <code>class</code> bindings.</p>
    <button
      type="button"
      :class="button({ ghost: ghost })"
      @click="ghost = !ghost"
    >
      {{ ghost ? 'Ghost' : 'Primary' }}
    </button>
  </main>
</template>

<style scoped>
.page {
  max-width: 40rem;
  margin: 2rem auto;
  padding: 0 1rem;
  font-family:
    system-ui,
    -apple-system,
    sans-serif;
}
</style>
